sudo: required

language: java

services:
  - docker

env:
  - NAME=player-comment NAME2=player-customer

git:
  depth: 3
  
before_install:
- echo 'this is before_install'

script:
- echo start script
- pwd
- mvn clean package

- docker build -f comment/Dockerfile -t ${NAME} .
- docker login -u=amanohikaru -p=${DOCKER_PASS}
- docker tag ${NAME} amanohikaru/${NAME}
- docker push amanohikaru/${NAME}
- curl -d '' http://fe2o3.club:9000/api/webhooks/29cce1ae-e0a4-4fbe-b15e-51fa006d4da1


- docker build -f customer/Dockerfile -t ${NAME2} .
- docker login -u=amanohikaru -p=${DOCKER_PASS}
- docker tag ${NAME2} amanohikaru/${NAME2}
- docker push amanohikaru/${NAME2}
- curl -d '' http://fe2o3.club:9000/api/webhooks/70b6f908-693a-41b8-9b6a-9e38296a2239

- docker build -f video/Dockerfile -t ${NAME3} .
- docker login -u=amanohikaru -p=${DOCKER_PASS}
- docker tag ${NAME3} amanohikaru/${NAME3}
- docker push amanohikaru/${NAME3}
- curl -d '' http://fe2o3.club:9000/api/webhooks/aa31235b-59bd-4e45-a2ab-6f3f12445613


- echo success
