#spring:
#  datasource:
#    url: ${MYSQL_URL:jdbc:mysql://39.104.226.149:3306/player?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT}
#    username: ${MYSQL_USER:root}
#    password: ${MYSQL_PASS:root}
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888

#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.performer.player.video.pojo
  
oss:
#  callback:
#    host: 
#    url: 
  endpoint: oss-cn-shanghai.aliyuncs.com
  access:
    id: LTAIdUg5ZuweKsAV
    key: OQSfGqKmeq03gYJTT4SD0IcRL5YTUo
  bucket: save-play
  dir: test/
  expire:
    time: 100
  policy:
    max:
      size: 1610612736