spring:
  datasource:
    url: jdbc:mysql://39.104.226.149:3306/player?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8089

